### ISSUE TITLE
Error on setup

### ISSUE THREAD

**Issue by bronzehedwick** [boltlessengineer/bufterm.nvim#1]
First of all, thanks so much for sharing your work!

I tried to setup the plugin via the default Packer snippet:

```lua
use {
  'boltlessengineer/bufterm.nvim',
  config = function()
    require('bufterm').setup()
  end,
}
```

Installation was successful, but I get a Packer error on setup:

```
packer.nvim: Error running config for bufterm.nvim: vim/shared.lua:0: after the second argument: expected table, got nil
```

**Comment by lalitmee** [comment]
@bronzehedwick, can you please try using this? Just pass an empty table(`{}`) in the `setup` function.

```lua
use {
  'boltlessengineer/bufterm.nvim',
  config = function()
    require('bufterm').setup({})
  end,
}
```

**Comment by boltlessengineer** [comment]
Thanks for opening the issue. Now fixed. `setup()` can be called with no argument.

**Comment by bronzehedwick** [comment]
Downloaded the update, and this is fixed. Thanks!
